// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@account-abstraction/contracts/core/BasePaymaster.sol";
import "@account-abstraction/contracts/interfaces/PackedUserOperation.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "./interfaces/IGhostPool.sol";
import "./interfaces/IGroth16Verifier.sol";

/// @title  GhostPaymaster
/// @author Ghost Privacy Suite
/// @notice ERC-4337 Paymaster that sponsors BNB gas for users who present
///         a valid Zero-Knowledge proof from the Ghost Privacy Pool.
///
/// @dev    ## Flow
///
///         1. User deposits USDC/USDT into GhostPool — gets a commitment.
///         2. Later, from a FRESH wallet with 0 BNB:
///            - User generates a ZK proof locally (never leaves the browser).
///            - User signs a `UserOperation` with `paymasterAndData` containing
///              this contract's address + the encoded ZK proof.
///         3. Backend relayer submits to a bundler (Pimlico) via `eth_sendUserOperation`.
///         4. EntryPoint calls `validatePaymasterUserOp()` on this contract:
///            - Decodes ZK proof from `paymasterAndData`.
///            - Verifies proof on-chain via `Groth16Verifier`.
///            - Checks Merkle root is canonical via `GhostPool.isKnownRoot()`.
///            - Checks nullifier is unspent.
///            - Approves gas sponsorship.
///         5. EntryPoint executes the `UserOperation`.
///         6. EntryPoint calls `_postOp()`:
///            - Marks nullifier as spent (prevents replay).
///            - Calls `GhostPool.deductFee()` to settle the gas cost in stablecoins.
///
///         ## Privacy Guarantee
///         The fresh wallet pays NO BNB from its own balance.
///         The ZK proof proves pool membership WITHOUT revealing which deposit.
///         The `recipient` public signal binds the proof to `userOp.sender`,
///         preventing relayers from re-using/stealing proofs.
///
///         ## paymasterAndData layout (v0.7 EntryPoint)
///         | Bytes     | Field                          |
///         |-----------|--------------------------------|
///         | [0:20]    | paymaster address              |
///         | [20:36]   | paymasterVerificationGasLimit  |
///         | [36:52]   | paymasterPostOpGasLimit        |
///         | [52:84]   | validUntil (uint256)           |
///         | [84:116]  | validAfter (uint256)           |
///         | [116:148] | feeToken address (padded)      |
///         | [148:]    | abi.encode(ZKProof)            |
///
contract GhostPaymaster is BasePaymaster {
    using SafeERC20 for IERC20;

    // ────────────────────────────────────────────────────────────────────────
    // Constants
    // ────────────────────────────────────────────────────────────────────────

    // PAYMASTER_DATA_OFFSET = 52 is inherited from BasePaymaster
    // (20 addr + 16 verGasLimit + 16 postOpGasLimit)

    // ────────────────────────────────────────────────────────────────────────
    // Immutables
    // ────────────────────────────────────────────────────────────────────────

    /// @notice The Ghost Privacy Pool — source of ZK commitments and fee balance.
    IGhostPool public immutable ghostPool;

    /// @notice On-chain Groth16 proof verifier (auto-generated by snarkjs).
    IGroth16Verifier public immutable verifier;

    // ────────────────────────────────────────────────────────────────────────
    // State
    // ────────────────────────────────────────────────────────────────────────

    /// @notice Tracks spent nullifier hashes — prevents proof replay.
    /// @dev    nullifierHash → true means this proof has already been used.
    mapping(bytes32 => bool) public nullifiers;

    /// @notice Gas price in USDC per 1 BNB of gas cost (18 dp precision).
    /// @dev    Set by owner. Used to convert actualGasCost (in wei) to USDC fee.
    ///         Example: if BNB = $600 and USDC has 6 dp:
    ///         rate = 600 * 10^6 * 10^18 / 10^18 = 600_000_000 (scaled)
    uint256 public bnbToUsdcRate;

    /// @notice Toggle ZK verification — set to false for testnet MVP (uses MockVerifier).
    ///         Set to true in production with the real Groth16Verifier.
    bool public zkVerificationEnabled;

    // ────────────────────────────────────────────────────────────────────────
    // Events
    // ────────────────────────────────────────────────────────────────────────

    event GasSponsored(
        address indexed sender,
        bytes32 indexed nullifierHash,
        uint256 gasCostWei,
        uint256 feeUSDC,
        address feeToken
    );

    event NullifierSpent(bytes32 indexed nullifierHash);

    event RateUpdated(uint256 oldRate, uint256 newRate);

    // ────────────────────────────────────────────────────────────────────────
    // Errors
    // ────────────────────────────────────────────────────────────────────────

    error InvalidZKProof();
    error UnknownMerkleRoot(bytes32 root);
    error NullifierAlreadySpent(bytes32 nullifierHash);
    error RecipientMismatch(address proofRecipient, address sender);
    error ProofExpired(uint256 validUntil, uint256 blockTime);
    error ProofNotYetValid(uint256 validAfter, uint256 blockTime);
    error InvalidPaymasterData();

    // ────────────────────────────────────────────────────────────────────────
    // Constructor
    // ────────────────────────────────────────────────────────────────────────

    /// @param _entryPoint      Canonical ERC-4337 EntryPoint address.
    /// @param _ghostPool       Deployed GhostPool contract.
    /// @param _verifier        Deployed Groth16Verifier (or MockGroth16Verifier for testing).
    /// @param _bnbToUsdcRate   Initial BNB→USDC conversion rate (scaled, see `bnbToUsdcRate`).
    /// @param _owner           Owner address (multisig in production).
    constructor(
        IEntryPoint _entryPoint,
        IGhostPool _ghostPool,
        IGroth16Verifier _verifier,
        uint256 _bnbToUsdcRate,
        address _owner
    ) BasePaymaster(_entryPoint) {
        require(address(_ghostPool) != address(0), "GhostPaymaster: zero pool");
        require(address(_verifier) != address(0), "GhostPaymaster: zero verifier");
        require(_bnbToUsdcRate > 0, "GhostPaymaster: zero rate");

        ghostPool = _ghostPool;
        verifier = _verifier;
        bnbToUsdcRate = _bnbToUsdcRate;
        zkVerificationEnabled = true; // default on; deploy with MockVerifier for MVP

        _transferOwnership(_owner);
    }

    // ────────────────────────────────────────────────────────────────────────
    // ERC-4337 Core — validatePaymasterUserOp
    // ────────────────────────────────────────────────────────────────────────

    /// @notice Validate whether this Paymaster will sponsor a given UserOperation.
    /// @dev    Called by EntryPoint before executing the UserOperation.
    ///         Must return within the verification gas limit.
    ///
    ///         Validation steps:
    ///         1. Decode paymasterData from `userOp.paymasterAndData[52:]`
    ///         2. Check proof timing (validUntil / validAfter)
    ///         3. Verify ZK proof on-chain via Groth16Verifier
    ///         4. Check public signals:
    ///            a. merkleRoot is known to GhostPool
    ///            b. nullifierHash is unspent
    ///            c. recipient == userOp.sender
    ///         5. Return context (passed to _postOp) + validationData (timing)
    function _validatePaymasterUserOp(
        PackedUserOperation calldata userOp,
        bytes32, /* userOpHash — not used, proof binds to sender instead */
        uint256  /* maxCost   — fee deducted in postOp */
    ) internal override returns (bytes memory context, uint256 validationData) {

        // ── 1. Decode paymasterData ──────────────────────────────────────────
        bytes calldata paymasterData = userOp.paymasterAndData[PAYMASTER_DATA_OFFSET:];

        if (paymasterData.length < 96) revert InvalidPaymasterData();

        (
            uint256 validUntil,
            uint256 validAfter,
            address feeToken,
            uint256[2]    memory pA,
            uint256[2][2] memory pB,
            uint256[2]    memory pC,
            uint256[3]    memory pubSignals
        ) = _decodePaymasterData(paymasterData);

        // ── 2. Timing checks ─────────────────────────────────────────────────
        if (validUntil != 0 && block.timestamp > validUntil)
            revert ProofExpired(validUntil, block.timestamp);
        if (validAfter != 0 && block.timestamp < validAfter)
            revert ProofNotYetValid(validAfter, block.timestamp);

        // ── 3. ZK proof verification ─────────────────────────────────────────
        if (zkVerificationEnabled) {
            bool valid = verifier.verifyProof(pA, pB, pC, pubSignals);
            if (!valid) revert InvalidZKProof();
        }

        // ── 4a. Merkle root check ─────────────────────────────────────────────
        bytes32 merkleRoot    = bytes32(pubSignals[0]);
        bytes32 nullifierHash = bytes32(pubSignals[1]);
        address recipient     = address(uint160(pubSignals[2]));

        if (!ghostPool.isKnownRoot(merkleRoot))
            revert UnknownMerkleRoot(merkleRoot);

        // ── 4b. Nullifier check ───────────────────────────────────────────────
        if (nullifiers[nullifierHash])
            revert NullifierAlreadySpent(nullifierHash);

        // ── 4c. Recipient binding ─────────────────────────────────────────────
        // The ZK proof must be bound to this specific sender.
        // Prevents a malicious bundler from re-routing the proof to a different UserOp.
        if (recipient != userOp.sender)
            revert RecipientMismatch(recipient, userOp.sender);

        // ── 5. Return context and validationData ──────────────────────────────
        // context is passed to _postOp — carry what we need to settle the fee.
        context = abi.encode(nullifierHash, feeToken, userOp.sender);

        // Pack validUntil + validAfter into ERC-4337 validationData.
        // Bit layout: [0] = sigFailed, [160:208] = validUntil, [208:256] = validAfter
        validationData = (uint256(uint48(validUntil)) << 160) | (uint256(uint48(validAfter)) << 208);
    }

    // ────────────────────────────────────────────────────────────────────────
    // ERC-4337 Core — _postOp
    // ────────────────────────────────────────────────────────────────────────

    /// @notice Settle gas costs after the UserOperation executes.
    /// @dev    Called by EntryPoint after execution. Even if the UserOp reverted,
    ///         this still runs in `PostOpMode.postOpReverted` — we still settle.
    ///
    ///         Steps:
    ///         1. Mark the nullifier as spent (idempotent — safe if called twice).
    ///         2. Convert actualGasCost (BNB wei) → USDC fee.
    ///         3. Deduct fee from GhostPool.
    function _postOp(
        PostOpMode mode,
        bytes calldata context,
        uint256 actualGasCost,
        uint256 /* actualUserOpFeePerGas */
    ) internal override {
        // Decode the context packed by _validatePaymasterUserOp.
        (bytes32 nullifierHash, address feeToken, address sender) =
            abi.decode(context, (bytes32, address, address));

        // ── 1. Spend nullifier ────────────────────────────────────────────────
        // Only mark as spent if not already (handles postOpReverted re-entry).
        if (!nullifiers[nullifierHash]) {
            nullifiers[nullifierHash] = true;
            emit NullifierSpent(nullifierHash);
        }

        // ── 2. Convert gas cost to USDC fee ───────────────────────────────────
        // feeUSDC = actualGasCost (wei) * bnbToUsdcRate / 10^18
        // bnbToUsdcRate is stored scaled by 10^18 to preserve precision.
        uint256 feeUSDC = (actualGasCost * bnbToUsdcRate) / 1e18;

        // In postOpReverted mode (UserOp execution reverted), we still charge
        // the gas cost — the user burned the proof, so the fee is still owed.
        // If the pool doesn't have enough balance, we absorb the cost (pool is
        // effectively insolvent for this nullifier — this is a known limitation).
        if (mode != PostOpMode.postOpReverted && feeUSDC > 0) {
            try ghostPool.deductFee(nullifierHash, feeUSDC, feeToken) {
                emit GasSponsored(sender, nullifierHash, actualGasCost, feeUSDC, feeToken);
            } catch {
                // Pool deduction failed (e.g. insufficient balance).
                // Gas was still sponsored — we absorb the loss.
                // The relayer backend will monitor and top up the pool.
                emit GasSponsored(sender, nullifierHash, actualGasCost, 0, feeToken);
            }
        }
    }

    // ────────────────────────────────────────────────────────────────────────
    // Admin
    // ────────────────────────────────────────────────────────────────────────

    /// @notice Deposit BNB into EntryPoint to fund gas sponsorship.
    function depositToEntryPoint() external payable onlyOwner {
        entryPoint.depositTo{value: msg.value}(address(this));
    }

    /// @notice Update the BNB→USDC conversion rate (scaled by 10^18).
    /// @dev    Call periodically via keeper or oracle. Ex: BNB=$600, USDC 6dp → rate=600_000_000
    function setRate(uint256 newRate) external onlyOwner {
        require(newRate > 0, "GhostPaymaster: zero rate");
        emit RateUpdated(bnbToUsdcRate, newRate);
        bnbToUsdcRate = newRate;
    }

    /// @notice Toggle ZK proof verification on/off.
    /// @dev    Set to false for MVP testing with MockGroth16Verifier.
    ///         MUST be true in production.
    function setZkVerificationEnabled(bool enabled) external onlyOwner {
        zkVerificationEnabled = enabled;
    }

    /// @notice Manually mark a nullifier as spent (emergency use only).
    function blacklistNullifier(bytes32 nullifierHash) external onlyOwner {
        nullifiers[nullifierHash] = true;
        emit NullifierSpent(nullifierHash);
    }

    // ────────────────────────────────────────────────────────────────────────
    // Internal helpers
    // ────────────────────────────────────────────────────────────────────────

    /// @dev Decode the custom paymasterData payload.
    ///
    ///      Layout (starts at paymasterAndData[52:]):
    ///      | Bytes    | Field                               |
    ///      |----------|-------------------------------------|
    ///      | [0:32]   | validUntil (uint256)                |
    ///      | [32:64]  | validAfter (uint256)                |
    ///      | [64:96]  | feeToken address (padded uint256)   |
    ///      | [96:]    | abi.encoded ZKProof struct          |
    ///
    ///      ZKProof abi.encode layout:
    ///      (uint256[2] pA, uint256[2][2] pB, uint256[2] pC, uint256[3] pubSignals)
    function _decodePaymasterData(bytes calldata data)
        private
        pure
        returns (
            uint256          validUntil,
            uint256          validAfter,
            address          feeToken,
            uint256[2]    memory pA,
            uint256[2][2] memory pB,
            uint256[2]    memory pC,
            uint256[3]    memory pubSignals
        )
    {
        // First 96 bytes are fixed fields
        validUntil = uint256(bytes32(data[0:32]));
        validAfter = uint256(bytes32(data[32:64]));
        feeToken   = address(uint160(uint256(bytes32(data[64:96]))));

        // Remaining bytes are the ABI-encoded ZK proof
        if (data.length > 96) {
            (pA, pB, pC, pubSignals) = abi.decode(
                data[96:],
                (uint256[2], uint256[2][2], uint256[2], uint256[3])
            );
        }
    }

    /// @dev Allow receiving BNB (for stake top-ups from plain transfers).
    receive() external payable {}
}
